# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: data-migration
  namespace: dataloader
stringData:
  bootstrap_server: "123"
  security_protocol: "123"
  sasl_mechanism: "123"
  sasl_username: "123"
  sasl_password: "123"
  s3_bucket: "s3://699955796816-ap-southeast-1-gft-dm-uat-athena-queries"
  database_name: "development_migrationdb"
  region_name: "ap-southeast-1"
  workgroup: "primary"

### PROD
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: secret-manager-for-data-migration
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: secret-manager-aws
#     kind: ClusterSecretStore
#   target:
#     name: account-service-rds-cred
#     creationPolicy: Owner
#     template:
#       type: Opaque
#   data:
#     - secretKey: bootstrap_server
#       remoteRef:
#         key: data-migration/stg
#         property: bootstrap_server
#     - secretKey: security_protocol
#       remoteRef:
#         key: data-migration/stg
#         property: security_protocol
#     - secretKey: sasl_mechanism
#       remoteRef:
#         key: data-migration/stg
#         property: sasl_mechanism
