[tox]
envlist = py38,py310
skipsdist = True

[testenv]
deps =
    pytest
    pytest-cov
commands =
    python3 -m pytest src/ci-348-framework-generacion-de-informes/test/ -v -p no:warnings --junitxml=logs/junit_report.xml --cov=src/ci-348-framework-generacion-de-informes --cov-config=tox.ini --cov-report=xml:logs/coverage.xml  --cov-report=html:logs/coverage

[coverage:run]
relative_files = True
#source = ci-348-framework-generacion-de-informes
branch = True
include =
    ci-348-framework-generacion-de-informes/**
    src/**


[testenv:clean]
deps = coverage
skip_install = false
commands = coverage erase