---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconciliator-api
  namespace: dataloader
spec:
  selector:
    matchLabels:
      app: reconciliator-api
  replicas: 5
  template:
    metadata:
      labels:
        app: reconciliator-api
    spec:
      serviceAccountName: data-migration-services
      imagePullSecrets:
      - name: regcredb 
      containers:
        - image: reconciliator-api
          name: reconciliator-api
          imagePullPolicy: Always
          env: []           
