apiVersion: batch/v1
kind: Job
metadata:
  name: global-reconciliator-account
  namespace: dataloader
spec:
  template:
    spec:
      serviceAccountName: data-migration-services
      imagePullSecrets:
      - name: regcredb
      containers:
      - name: global-reconciliator-account
        image: global-reconciliator-api
        imagePullPolicy: Always
        env:
          - name: ENTITY
            value: "account"       
      restartPolicy: Never
  backoffLimit: 0     